proxmox:
  children:
    kovalhome:
      children:
        nodes:
          hosts:
            pve.mgmt.home.local.koval.net:
            pve2.mgmt.home.local.koval.net:
        managed:
          children:
            cloud:
              hosts:
                cloud.srv.home.local.koval.net:
            photos:
              hosts:
                photos.srv.home.local.koval.net:
            secrets:
              hosts:
                secrets.srv.home.local.koval.net:
            music:
              hosts:
                music.srv.home.local.koval.net:
            samba:
              hosts:
                samba.srv.home.local.koval.net:
            finance:
              hosts:
                finance.srv.home.local.koval.net:
            solidtime:
              hosts:
                solidtime.srv.home.local.koval.net:
            rmfakecloud:
              hosts:
                rmfakecloud.srv.home.local.koval.net:
            homeassistant:
              hosts:
                homeassistant.srv.home.local.koval.net:
          vars:
            ansible_user: debian
            ansible_ssh_private_key_file: ~/.ssh/id_rsa
            ansible_ssh_common_args: -o StrictHostKeyChecking=accept-new # TODO: Improve this
        unmanaged:
          children:
            backups:
              hosts:
                backups.srv.home.local.koval.net:
            unifi:
              hosts:
                unifi.srv.home.local.koval.net:
            coolify:
              hosts:
                coolify.srv.home.local.koval.net:
          vars:
            ansible_user: debian
            ansible_ssh_private_key_file: ~/.ssh/id_rsa
            ansible_ssh_common_args: -o StrictHostKeyChecking=accept-new # TODO: Improve this
      vars:
        infisical_project: d102ada3-7d49-4138-9759-033ca79fe731
