version: "3"

services:
  navidrome:
    image: deluan/navidrome:latest
    restart: unless-stopped
    user: 1000:1000
    ports:
      - 4533:4533
    env_file: .env
    environment:
      - ND_BASEURL=https://music.koval.net
      - ND_LASTFM_APIKEY=${LASTFM_APIKEY}
      - ND_LASTFM_SECRET=${LASTFM_SECRET}
      - ND_SPOTIFY_ID=${SPOTIFY_ID}
      - ND_SPOTIFY_SECRET=${SPOTIFY_SECRET}
      - ND_COVERARTPRIORITY=cover.*, folder.*, front.*, external, embedded
    volumes:
      - navidrome_data:/data
      - /mnt/media/music:/music:ro
  yubal:
    image: ghcr.io/guillevc/yubal:latest
    restart: unless-stopped
    ports:
      - 8000:8000
    environment:
      PUID: 1000
      PGID: 1000
      YUBAL_SCHEDULER_CRON: "0 0 * * *"
      YUBAL_DOWNLOAD_UGC: false
      YUBAL_TZ: Europe/London
    volumes:
      - yubal_config:/app/config
      - /mnt/media/music:/app/data

volumes:
  navidrome_data:
  yubal_config:
  filebrowser_config:
